-- CreateEnum
CREATE TYPE "public"."AutomationStage" AS ENUM ('TRIAGE', 'DILLIGENCE_OPERATIONAL', 'DILLIGENCE_COMMERCIAL', 'DILLIGENCE_FINANCIAL', 'DILLIGENCE_CAP_TABLE_AND_LEGAL_REVIEW');

-- AlterTable
ALTER TABLE "public"."automations" ADD COLUMN     "stage" "public"."AutomationStage" NOT NULL DEFAULT 'TRIAGE',
ALTER COLUMN "status" SET DEFAULT 'NOT_STARTED';
