export const EMAIL_ERROR_CODES = {
    PROVIDER_ERROR: 1000,
    CONFIGURATION_ERROR: 1001
} as const

export type EmailErrorCode = typeof EMAIL_ERROR_CODES[keyof typeof EMAIL_ERROR_CODES]

export enum EmailErrorType {
    PROVIDER_ERROR = "PROVIDER_ERROR",
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
    MISSING_NOTIFICATION_EMAIL = "MISSING_NOTIFICATION_EMAIL",
    SEND_ERROR = "SEND_ERROR",
    MISSING_SENDER_EMAIL = "MISSING_SENDER_EMAIL",
    MISSING_DESTINATION_EMAIL = "MISSING_DESTINATION_EMAIL"
} 