apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcpsm-secret-store-agent
  namespace: prod
spec:
  provider:
    gcpsm:
      projectID: "your-gcp-project-id"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: your-gke-cluster
          serviceAccountRef:
            name: diligence-kit-agent
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diligence-kit-agent-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store-agent
    kind: SecretStore
  target:
    name: diligence-kit-agent-secret
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: diligence-kit-agent-openai-api-key-prod
    - secretKey: google-cloud-project-id
      remoteRef:
        key: diligence-kit-agent-gcp-project-id-prod
    - secretKey: google-cloud-bucket-name
      remoteRef:
        key: diligence-kit-agent-gcp-bucket-name-prod
    - secretKey: agent-secret
      remoteRef:
        key: diligence-kit-service-agent-secret-prod
    - secretKey: backend-base-url
      remoteRef:
        key: diligence-kit-agent-backend-base-url-prod
    - secretKey: api-key
      remoteRef:
        key: diligence-kit-agent-api-key-prod
    - secretKey: webhook-secret
      remoteRef:
        key: diligence-kit-agent-webhook-secret-prod
