apiVersion: v1
kind: ServiceAccount
metadata:
  name: diligence-kit-agent
  namespace: prod
  annotations:
    iam.gke.io/gcp-service-account: "diligence-kit@your-gcp-project-id.iam.gserviceaccount.com"
