apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diligence-kit-liaison-app-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: diligence-kit-liaison-app-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: diligence-kit-liaison-api-key-prod
    - secretKey: gcp-project-id
      remoteRef:
        key: diligence-kit-liaison-gcp-project-id-prod
    - secretKey: gcp-location
      remoteRef:
        key: diligence-kit-liaison-gcp-location-prod
    - secretKey: env
      remoteRef:
        key: diligence-kit-liaison-env-prod
    - secretKey: log-level
      remoteRef:
        key: diligence-kit-liaison-log-level-prod
    - secretKey: host
      remoteRef:
        key: diligence-kit-liaison-host-prod
    - secretKey: port
      remoteRef:
        key: diligence-kit-liaison-port-prod
    - secretKey: database-url
      remoteRef:
        key: diligence-kit-liaison-database-url-prod
