apiVersion: "v1"
kind: "Service"
metadata:
  name: "diligence-kit-liaison-agent"
  namespace: "prod"
spec:
  type: NodePort
  selector:
    app: "diligence-kit-liaison-agent"
  ports:
  - port: 8000
    targetPort: 8000
    name: http
